version: "3.7"
services:
  
  team_1_api:
    build: .
    image: team_1_api_image
    container_name: team_1_api_container
    ports:
      - "8001:8001"
    links:
      - team_1_postgres_app
    env_file:
      - .env

  team_1_postgres_app:
    image: postgres
    container_name: team_1_postgres_container
    ports: 
      - "5432:5432"
    env_file:
      - .env.db.docker
    volumes:
      - team_1_postgres:/var/lib/postgresql/data

volumes:
  team_1_postgres: